package JavaWSDLFahrenheitConverter.forras;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Date;



public interface AFDDateTimeConverter
{
    Date convertDateTime(String strDate);
    Date convertTime(String strDate);
    Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}